using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dnata.TravelRepublic.MobileWeb.UI.Models;

namespace Dnata.TravelRepublic.MobileWeb.UI.Interfaces
{
    public interface IHotelEstabPage : IBase
    {
        string GetHotelName();
        int GetHotelStarRating();
        string GetHotelLocation();
        string GetHotelRating();
        decimal GetHotelPrice();
        decimal GetHotelWasPrice();
        string GetSahLabelText();
        string GetHotelPillText();
        decimal GetBoardWasPrice(int count = 0);
        decimal GetBoardNowPrice(int count = 0);
        string GetBoardPromoMessage(int count=0);
        string GetRoomPromoMessage(int count = 0);
        decimal GetHotelPerPersonPrice();
        decimal GetHolidayPrice();
        decimal GetHolidayPerPersonPrice();
        void SelectRoom(int RoomNo);
        string GetSelectedRoomType(int roomNo);
        decimal GetSelectedRoomPrice(int roomNo);
        void SelectBoardType(int boardTypeNo);
        string GetBoardType(int boardTypeNo);
        RoomInformation GetRoomInformation(int roomNo);
        BoardTypeInformation GetBoardTypeInformation(int roomNo);
        void SelectRoomsAndBoardTypes(int NoOfRooms, string boardType = "");
        void SelectDistinctRoomsTypesOnMobile(int NoOfRooms);
        List<RoomInformation> GetSelectedRoomTypes();
        List<BoardTypeInformation> GetSelectedBoardTypes();
        int GetRoomTypeCount();
        int GetBoardTypeCount();
        void SelectPerPersonPriceToggle();
        void SelectTotalPriceToggle();
        void MoveToRoomsTab();
        string GetSearchItinerary();
        int GetCheckinDayfromSearchItinerary();
        string GetLocalTaxes();
        void CloseLocalTaxPopup();
        bool VerifyDefaultSelectedPrice();
        string GetTotalPriceToggleSwitchBackgorundColor();
        string GetPerPersonPriceToggleSwitchBackgorundColor();
        void ViewFlightDetails();
        bool IsBoardTypeDisplayedInPriceIncludesSection();
        void VerifyOverviewTab();
        void ClickOverviewTab();
        void ClickRoomsTab();
        void ClickReviewsTab();
        void VerifyHotelInformationSection();
        void VerifyHotelInfoToggleSwitch();
        void VerifyFacilitiesSection();
        List<string> GetFacilities();
        void VerifyReviewsSectionInOverView();
        void ClickSeeAllCustomerReviews();
        int GetReviewsCount();
        void ClickSeeMoreReviews();
        bool VerifyReviewsDisplayedInAscendingOrderByDate();
        void VerifySeeWholeReview();
        void VerifyNoReviewsMessage();
        int GetDesktopBoardTypeCount(int room = 1);
        BoardTypeInformation GetDesktopBoardTypeInformation(int boardToSelect, int room = 1);
        void SelectDesktopBoardType(int boardToSelect, int room = 1);
        string GetPriceCaption();
        string GetContinueButtonText();
        bool IsEstabPageDisplayed();
        bool ValidatePropertyAmenities(string filteredOption);
        bool ValidateBoardType(string filterdBoardType);
        bool ValidatePropertyAmenities(List<string> filteredOptions);
        bool IsChooseRoomsButtonDisplayed();
        void ClickChooseRoomButton();
        bool IsRoomsTabSelected();
        bool IsRoomsTabScrolledToTop();
        void ClickShowWholeReviewLink();
        bool IsShowLessLinkDisplayed();
        bool IsReviewContentFaded();
        bool IsSeeAllReviewsDisplayed();
        bool IsYourRoomOptionsButtonDisplayed();
        void ClickYourRoomOptionsButton();
        int GetPriceIncludesOptionsCount();
        bool IsSecureTodayPillDisplayed();
        decimal GetDepositPriceFromSecurePill();
        void ClickSecureTodayPill();
        bool IsFreeCancellationLinkDisplayed();
        void ClickFreeCancellationMessage();
        string GetFreeHotelCancellationTextInPriceIncludesSection();
        string GetFreeHotelCancellationTextInBoardType(int roomType, int boardType);
        bool IsPayMonthlyPillDisplayed();
        decimal GetAmountFromPayMonthlyPill();
        void ClickPayMonthlyPill();
        bool IsReturnTransfersMessageDisplayed();
        string GetRoomNumberColor(int roomNo);
        string GetRoomHeaderText();
        string GetToastMessage();
        void ClickRoomSelectionBadge(int roomNo);
        bool IsYourRoomStickyButtonDisplayed();
        void ClickYourRoomStickyButton();
        bool IsLocalChargesMessageDisplayed();
        void ClickLocalChargesMessage();
        bool IsPreSelectedRoomDisplayed();
        string GetPreSelectedRoomType();
        string GetPreSelectedBoardType();
        decimal GetPreSelectedRoomPrice();
        bool IsFreeCancellationMessageDisplayedInBoardType();
        bool IsSecureTodayPillDisplayedInBoardType();
        bool IsPayMonthlyPillDisplayedInBoardType();
        string SelectRandomBoardFilter();
        void ClickBackToRooms();
        bool IsHolidayJourney();
        string GetBoardTypeInEstabPriceIncludeSection();
        bool IsNonRefundable();
        void ClickOnNonRefundableMessageLink();
        int GetRooomToSelectByName(string roomName);
        int GetBoardToSelectByNameInGivenRoom(int room, string boardType);
        List<string> GetAllBoardTypeNames();

    }
}
